### ISSUE TITLE
When participants failed the comprehension task, the feedback should specify which question is failed.

### ISSUE THREAD

**Issue by liushi0104** [zeroztz/public-goods#10]

**Comment by zeroztz** [comment]
I thought it was intended to not show failed questions specifically. Otherwise participant could just guess and retry.

But I can make it an option when you create the experiment. And you can choose to allow or not allow participant see the failed questions.

**Comment by zeroztz** [comment]
I just show the questions they failed. If you want me to make this optional just reopen this bug
