### ISSUE TITLE
The total round should be 8 (now it seems to run forever)

### ISSUE THREAD

**Issue by liushi0104** [zeroztz/public-goods#11]

**Comment by zeroztz** [comment]
What do you want me to show after it's finished. I will just show a empty page with "The game is ended. Thanks!"

**Comment by liushi0104** [comment]
Show total points and ask them to report the points to the experimenter

**Comment by zeroztz** [comment]
Do they need to report to experiment? because total points will be available online.

**Comment by liushi0104** [comment]
We will have to pay them on the spot, so it would be great that they know
their points.

Thanks.

**Comment by zeroztz** [comment]
Oh. Got it.

Do you want me to also translate points in to $ that they earn?

**Comment by liushi0104** [comment]
Points will do - thanks!

**Comment by zeroztz** [comment]
I made the change to show final result when the # of total rounds is '8'. And also make this '8' as an option when you create exp so you can easily test it out.

**Comment by liushi0104** [comment]
awesome! Thank you very much!!
