### ISSUE TITLE
In one round, one participant contributed shown as "NaN" not sure what happend. As a result, the total point for everyone became NaN 

### ISSUE THREAD

**Issue by liushi0104** [zeroztz/public-goods#14]
![1](https://user-images.githubusercontent.com/15862030/28944332-389a3f58-7870-11e7-8b2c-c5d0178526f3.JPG)

**Comment by zeroztz** [comment]
Do you have the participant id so I can check in database?

If this bug is not reproducible, I cannot fix it.

**Comment by liushi0104** [comment]
That’s too long along. Let’s hope that it won’t appear again.

**Comment by zeroztz** [comment]
Unfortunately, those data are gone. So I cannot find the participant on cloud either. Let's close the bug. and if we see this again, we can take another look.
