### ISSUE TITLE
In the kick game, if a participant is excluded in round N, he shouldn't be able to vote in the next round.

### ISSUE THREAD

**Issue by liushi0104** [zeroztz/public-goods#18]

**Comment by zeroztz** [comment]
I assume you are saying (s)he should not be able to vote KICK in the next round.

One more question: will (s)he be able to be kicked in next round?

**Comment by liushi0104** [comment]
If the person is not in the game, then he shouldn't be able to be kicked in
the next round.

Thanks!

**Comment by zeroztz** [comment]
Done. Code fixed. Test added. This will be fixed in next release.

One last question: if they are kicked, should they see what other participants contributed?
