### ISSUE TITLE
round number

### ISSUE THREAD

**Issue by liuzj09** [zeroztz/public-goods#20]
After the last round (e.g., round 6), it will show round 7/6. Is it possible to not show the wrong round number?

**Comment by liushi0104** [comment]
A Related Issue:

When posting results for Round 1, it shows as Round 2/6.
When posting results for Round 2, it shows as Round 3/6.
...
When posting results fro Round 6, it shows as Round 7/6.

**Comment by zeroztz** [comment]
Done.
