### ISSUE TITLE
Fake reputation-claimed contribution 

### ISSUE THREAD

**Issue by liuzj09** [zeroztz/public-goods#21]
For experiments fake reputation, when the actual contribution and claimed contribution are the same, it is said you didn’t select any contribution. When tried again, it worked. 

Also, we might need to change the warning message when the claimed contribution is less than the actual contribution. Currently, it says you didn't select any contribution. We could say something like: your claimed contribution should be the same or larger than your actual contribution.

**Comment by liushi0104** [comment]
Yes, I encountered the same. The warning message should be something like

"Your claimed contribution can not be lower than your actual contribution. Please select again."

**Comment by zeroztz** [comment]
Done
